version: '3.8'

services:
  go-server:
    build: .
    command: go run .
    ports:
      - "8080:8081"
    volumes:
      - .:/app
    working_dir: /app

  y-websocket:
    build: .
    command: npx y-websocket
    environment:
      - HOST=0.0.0.0
      - PORT=8082
    ports:
      - "8082:8082"
    volumes:
      - .:/app
    working_dir: /app